Algoritmo "maiorZero"
//
//
// Descrição   : Solicite ao usuário um número inteiro, repita a leitura até
//              que seja informado um número maior que zero. Depois exiba o
//              número digitado. Estrutura: REPITA.
// Autor(a)    : Rafael Carvalho Senger
// Data atual  : 06/08/2026
Var
   // Seção de Declarações das variáveis
   n : inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   repita
      escreval("Insira um numero:")
      leia(n)
   ate (n > 0)

Fimalgoritmo