Algoritmo "semnome"
// 
//  
// Descrição   :Leia um número N digitado pelo usuário e imprima de 1 até N,
//             de dois em dois. Estrutura: PARA.

// Autor(a)    : Rafael Carvalho Senger
// Data atual  : 06/08/2026
Var
// Seção de Declarações das variáveis 
n, i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Insira um numero inteiro:")
leia(n)
para i de 1 ate n passo 2 faca
     escreval(i)
fimpara

Fimalgoritmo